# Generated by Django 5.1.2 on 2025-03-04 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0003_alter_image_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_spring', models.CharField(blank=True, max_length=5, verbose_name='Уровень сложности весной')),
                ('level_summer', models.CharField(blank=True, max_length=5, verbose_name='Уровень сложности летом')),
                ('level_autumn', models.CharField(blank=True, max_length=5, verbose_name='Уровень сложности осенью')),
                ('level_winter', models.CharField(blank=True, max_length=5, verbose_name='Уровень сложности зимой')),
            ],
        ),
        migrations.RemoveField(
            model_name='pereval',
            name='level_autumn',
        ),
        migrations.RemoveField(
            model_name='pereval',
            name='level_spring',
        ),
        migrations.RemoveField(
            model_name='pereval',
            name='level_summer',
        ),
        migrations.RemoveField(
            model_name='pereval',
            name='level_winter',
        ),
        migrations.AddField(
            model_name='pereval',
            name='levels',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='pereval.levels'),
            preserve_default=False,
        ),
    ]
